[theme]
base = "dark"
primaryColor = "#D99A73"
backgroundColor = "#17141D"
secondaryBackgroundColor = "#24202E"
textColor = "#F1EAE4"
font = "sans serif"

[client]
toolbarMode = "minimal"
address = "127.0.0.1"